### ISSUE TITLE
sentinal: exited abnormally with code 255 

### ISSUE THREAD

**Issue by SreenivasVRao** [stsquad/dired-rsync#14]
Hi, thanks a lot for this package. I get this error when I try to rsync with a remote machine. Any idea why that might be happening?

**Comment by stsquad** [comment]
Can you run M-x list-processes and visit the rsync buffer and see what it's contents are? Where there any funny characters in your filenames? I think I've run into some escaping issues before.

**Comment by stsquad** [comment]
In fact you should be able to visit the rsync process buffer and see what went wrong.

**Comment by SreenivasVRao** [comment]
thanks, it was an issue with the command. the rsync buffer had the info!
