### ISSUE TITLE
share two functions for file operations in the background

### ISSUE THREAD

**Issue by QiangF** [stsquad/dired-rsync#16]
I'd like to share some functions for file operations in the background.

Smart move file and dirs: 
1. use git mv in a git repo, works well with git (and git-annex) 
2. use rsync for non git controlled files
3. does not break relative symlinks

Smart copy file and dirs: 
1. use hardlink for files on the same file system
2. use rsync for files on different file systems
3. does not break relative symlinks

Here is the link:
https://gist.github.com/QiangF/00825d4f1e28b53d45bbf5efb526c95d

**Comment by stsquad** [comment]
Thanks for your comment but I'm unsure what the aim is. Is there some additional functionality you'd like to add to dired-rsync? Or do you think some of the functions could be replaced by async functions? Either way you would need to submit a PR detailing how the changes to dired-rsync would be made.

**Comment by QiangF** [comment]
I was just suggesting if these features are useful for others, maybe some dired-rsync users can make it better. Sorry for making this weird issue.
