### ISSUE TITLE
Transfer fails if Tramp ssh path contains port number

### ISSUE THREAD

**Issue by alexvorobiev** [stsquad/dired-rsync#18]
I am using ssh tunnel to connect to a server. Tramp uses `#` to separate port number from the host name. I am guessing dired-rsync needs to replace `#port` with `-p port` which is what rsync expects.
```
ssh: Could not resolve hostname localhost#2222: Name or service not known

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

**Comment by stsquad** [comment]
Yes - we need to expand the handling of the file parts. A quick workaround would be to set up an alias in .ssh/config and then drop the port number from your tramp path.
