### ISSUE TITLE
error in process filter: No buffer named [whatever]

### ISSUE THREAD

**Issue by ieure** [stsquad/dired-rsync#19]
If you start a dired-rsync, then kill the buffer, `dired-rsync--filter` will produce "No buffer named [whatever]" (where "[whatever]" is the name of the dired buffer rsync was started from) errors every time it's evaluated -- approximately once a second -- until the rsync completes.  Emacs is near unresponsive during this time.

The issue is [this call to `with-current-buffer`](https://github.com/stsquad/dired-rsync/blob/3eb1ff3ded8e2881606459cf6e64cf28d8062b64/dired-rsync.el#L215).  The symptom is trivially fixable with something like:

```emacs-lisp
(let ((buf (plist-get details ':dired-buffer)))
  (when (buffer-live-p buf)
    (with-current-buffer buf
      (dired-rsync--update-modeline err indicator))))
```

But I'm not convinced this is the right approach.  Even though it fixes the immediate problem, you're left without any indication that the process is ongoing, or way to know when it's completed.  And I think if you fix *that*, then the issue of the original dired buffer being killed also goes away.

**Comment by stsquad** [comment]
Internally the update-modeline code uses mode-line-process which is buffer local. So the question is what do we do in the case the dired-buffer is closed? Just use which ever buffer is currently live and tramp over it's mode-line-process?

**Comment by ieure** [comment]
Setting any particular buffer's modeline is going to have the same issue.  I think the right thing to do is to have a global status.  I know things like `erc-track` are able to do this, but I haven't looked at the mechanism.  I know you can add something to every buffer's modeline if you `setq-default` `mode-line-format`, so that's probably a viable approach.

**Comment by stsquad** [comment]
I don't thing we can override the main mode-line variable but I'll look at
the erc approach.

**Comment by ieure** [comment]
It looks like ERC adds `'(t erc-modified-channels-object)` to `mode-line-modes`, which is already in `mode-line-format`; so it doesn't have to change the global one.  The `t` tells Emacs to display that object, and `erc-modified-channels-object` itself is the text to insert.  In ERC's case, it has properties for color and local keymays.  This stuff is managed in `erc-track-add-to-mode-line`.
