### ISSUE TITLE
It does not work for remote-to-local, local-to-remote, remote-to-remote

### ISSUE THREAD

**Issue by fu123456** [stsquad/dired-rsync#23]
You said," you can use rsync to copy files locally the main use case is copying files to/from a remote system. " and "You can also do a remote-to-remote copy although this does involve setting up a port forward so the first remote can access the second remote. It’s ugly but it works." But I test this code, found that it does not work. I want to know did you have tested this code for transferring files. It does Not work at all, but it does not output any message.

**Comment by fu123456** [comment]
@stsquad

**Comment by stsquad** [comment]
I use remote-to-remote regularly at home to copy from a remote machine to my nas. Look at the *rsync* process buffer and tell me what it says.

**Comment by fu123456** [comment]
In my local, it also does not work. The buffer shows:
cmd:rsync -avR --info=progress2 /home/lh/Temp/RoG_plus-master.zip /home/lh/Temp/temp_fg/
0 marks removed

but it does not rsync files.

**Comment by fu123456** [comment]
Hi, 
Moreover, the rsync buffer outputs the following information:
fugang@202.***.***.***'s password:
So do you have any solution to cope with this issue?

**Comment by fu123456** [comment]
@stsquad

**Comment by stsquad** [comment]
As mentioned in the readme:

>  The rsync tool is always run locally as rsync needs working SSH authentication to work

So it seems to me you don't have ssh keys setup and/or the emacs process that spawns rsync hasn't got a connection to your authentication agent.

**Comment by fu123456** [comment]
Ok. Now I have correctly configured for rsync, and does not need to input password. But I execute dired-rsync, it also seemly does not work and output
cmd:rsync -avR --info=progress2 /home/lh/Temp/batch_image fugang@202.***.***.***:"/home/lh/"
0 marks removed
Acturally, there is no file rsyned to remote.

**Comment by fu123456** [comment]
Thanks. It does work.

**Comment by arstum** [comment]
How nas to nas?

**Comment by arstum** [comment]
How to implement remote to remote with an ugly port forward hack?
