### ISSUE TITLE
Missing username in rsync comand

### ISSUE THREAD

**Issue by liebkne** [stsquad/dired-rsync#26]
When I try to `rsync` files from remote to local, I see the `R:1` in modeline. Using `ps -ef | grep rsync` I find the command `rsync -az --info=progress2 192.168.2.166:/home/user/git/skyroc-ai-docs/markdown /Users/user/Downloads/` is being used. It seems that the username is missing before host name and the process is hung.

**Comment by stsquad** [comment]
I think this should now be fixed in master.
