### ISSUE TITLE
^M in the process buffer

### ISSUE THREAD

**Issue by yitang** [stsquad/dired-rsync#36]
I'm not sure if this is related to dired-rsync, but I see a lot of ^M character in the process buffer. I couldn't find a solution to get rid of them to have a nice process bar in the buffer. 

I wonder if you have any ideas? 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/6054101/181195231-925ae4ab-6014-4f9d-9d51-4c97a0df4a47.png">

**Comment by stsquad** [comment]
I expect it is a a CR (without a newline). However we do extract the completion percentage in `dired-rsync--filter` and expose it via dired-rsync-modeline-status for the modeline. You could do something with that?

**Comment by linktohack** [comment]
Just happen to see this as well, and this patch works for me

```emacs-lisp
  (el-patch-feature dired-rsync)

  (with-eval-after-load 'dired-rsync
    (el-patch-defun dired-rsync--do-run (command details)
      "Run rsync COMMAND in a unique buffer, passing DETAILS to sentinel."
      (let* ((buf (format "%s @ %s" dired-rsync-proc-buffer-prefix (current-time-string)))
	     (el-patch-add (default-process-coding-system '(mac . mac)))
	     (proc (start-process-shell-command "*rsync*" buf command)))
	(set-process-sentinel
	 proc
	 #'(lambda (proc desc)
	     (dired-rsync--sentinel proc desc details)))
	(set-process-filter
	 proc
	 #'(lambda (proc string)
	     (dired-rsync--filter proc string details)))
	(dired-rsync--update-modeline)))

```

Basically the coding system is wrongly recognised.

**Comment by stsquad** [comment]
So is this a bug in the underlying process spawning code?

**Comment by xor-xor** [comment]
I think that this is slightly more nuanced ;) Here's my take: `dired-rsync` calls `start-process-shell-command`, which in turn calls `start-process`, which calls `make-process`, and then we finally reach`find-operation-coding-system` (called as a C function) - if this last call is unable to succeed, then `default-process-coding-system` is used, which on my mac with Emacs 28.2 happens to be `(utf-8-unix . utf-8-unix)`.

Moreover, if we look at the docstring of `find-operation-coding-system` function, we will find this:
```
This function looks up what is specified for TARGET in
`file-coding-system-alist', `process-coding-system-alist',
or `network-coding-system-alist' depending on OPERATION.
They may specify a coding system, a cons of coding systems,
or a function symbol to call.
```
On my mac, `process-coding-system-alist` is `nil` by default, but when I change it to e.g.:
```
(setq process-coding-system-alist '(("sh" . mac)))
```
...then I'm getting nicely formatted output in the process buffer :) 

(btw, I'm testing this locally, hence `"sh"` regexp, but I think this will work remotely too, as `ssh` is being used under the hood)

So, what I'm trying to say is that there are many ways to skin a cat with Emacs ;) As you can see, the same result can be achieved by manipulating `default-process-coding-system` (as per @linktohack's answer) or `process-coding-system-alist` - and who knows what else. Which one should be considered as "canonical" and who is "responsible" for setting those values (i.e. you or your users)? Are there other ways of spawning subprocesses, which allow to explicitly specify the coding system for input/output? These are the questions that I'd like to answer, but I didn't have time to dig further, so I'm leaving my observations here.

**Comment by yitang** [comment]
@xor-xor thanks for the fix. the progress bar on macOs looks nice. but now i see the same issue on linux. i will follow up after a few experiments. 

![image](https://user-images.githubusercontent.com/6054101/213923645-18489af3-3ede-49cd-b779-bd55ae14d157.png)

**Comment by yitang** [comment]
so on my debian system, it's running gnome. the progress bar got fixed by using the mac's coding system below. see the highlighted line with the changes i made. 
 
![image](https://user-images.githubusercontent.com/6054101/213924045-1dcfe042-6cc5-4926-b495-90398e93149d.png)

Is there a better way to fix it for all systems? 

note on debian, 
1. I have `default-process-coding-system` set to `(utf-8-unix . utf-8-unix)`
2. `process-coding-system-alist` set to nil 


Thanks,
Yi

**Comment by xor-xor** [comment]
> Is there a way to fix it for all systems?

I guess there is, by e.g. extending this condition that you've highlighted. But first, I'd like to establish that it is indeed broken, as the need to use `:coding 'mac` on Linux looks a bit suspicious to me. Having said that, I need some time to examine it (say, couple of days), as I don't have a Linux box with Emacs at hand right now.

What is your version of Emacs, BTW?

**Comment by yitang** [comment]
I'm running Emacs 29.0.60. I was surprised to see `:coding 'mac` worked and I agree with you. 

let me know if you want me to do more tests now or later. 

Thanks,
Y

**Comment by stsquad** [comment]
I have an idea which might kill two birds with one stone - lets delete everything upto the newline. This will help solve #39

**Comment by stsquad** [comment]
Can you review the proposed fix please?
