### ISSUE TITLE
Support adjusting rsync options using the transient UI

### ISSUE THREAD

**Issue by ilupin** [stsquad/dired-rsync#40]
Hi, it would be convenient that rsync options are shown and can be adjusted after invoking the `dired-rsync` command, just like magit. I can submit a patch. What do you think? Thanks.

**Comment by stsquad** [comment]
Are you suggesting a transient pop-up to alter dired-rsync-command and dired-rsync-options? I'm not sure if I would want to add the additional dependency to the core package but it would certainly be worthwhile either as a contrib/ package or just documentation. How complex is what you are suggesting?

**Comment by ilupin** [comment]
You can find the code [here](https://github.com/stsquad/dired-rsync/compare/master...ilupin:dired-rsync:master). I add a separate command `dired-rsync-transient`, which can alter `dired-rsync-options` temporarily when executing `dired-rsync`.

**Comment by ilupin** [comment]
Thanks, I have updated the code and opened a PR. Could you take a look?
