### ISSUE TITLE
When will it be done

### ISSUE THREAD

**Issue by arstum** [stsquad/dired-rsync#43]
How do we know when it's done

**Comment by stsquad** [comment]
There is a variable called `dired-rsync-modeline-status` which is intended for use in mode-lines, for example:

```
;; Enable dired-rsync
(use-package dired-rsync
  :hook (dired-mode . (lambda () (setq-local mode-line-process
                                             'dired-rsync-modeline-status)))
  :config
  (bind-key "C-c C-r" 'dired-rsync dired-mode-map))
```

**Comment by arstum** [comment]
after:
(package-install 'dired-rsync)
(add-hook 'dired-mode '(lambda () (setq-local mode-line-process
                                             'dired-rsync-modeline-status)))

did not take effect

**Comment by stsquad** [comment]
Does the value of dired-rsync-modeline-status change while the rsync is running? Have you tried switching to the rsync process buffer to see if something went wrong? You can set the dired-rsync-failed-hook to dired-rsync--pop-to-rsync-failed-buf if you want it to do it automatically.

**Comment by arstum** [comment]
(add-to-list 'mode-line-format mode-line-process)
(add-hook 'dired-mode-hook '(lambda () (setq-local mode-line-process 'dired-rsync-modeline-status)))

It's work.

**Comment by stsquad** [comment]
Ahh I suspect mode-line-process was auto added to my modeline by the modeline package I use. I'll see if I can clear up the documentation to make it clearer.

**Comment by arstum** [comment]
@stsquad 3Q
