### ISSUE TITLE
can not kill this error (search-failed "\15")

### ISSUE THREAD

**Issue by arstum** [stsquad/dired-rsync#49]
Debugger entered--Lisp error: (search-failed "\15")
  search-backward("\15")
  dired-rsync--filter(#<process *rsync*> "sending incremental file list\n")
  #f(compiled-function (proc string) #<bytecode 0x1aabd8648c0fd8c5>)(#<process *rsync*> "sending incremental file list\n")

**Comment by arstum** [comment]
init.el
(package-install 'dired-rsync)

**Comment by arstum** [comment]
;; (define-key minibuffer-local-map [remap isearch-backward] 'consult-history),deal

**Comment by stsquad** [comment]
Can you check the current master and see if that fixes it for you?

**Comment by arstum** [comment]
Failed.same situation.
Debugger entered--Lisp error: (search-failed "\15")
  search-backward("\15")
  dired-rsync--filter(#<process *rsync*> "\n")
  #f(compiled-function (proc string) #<bytecode 0x1aabd8657a575305>)(#<process *rsync*> "\n")

**Comment by stsquad** [comment]
For reference fixed by: 5bcb851f3bf9c4f7c07299fcc25be7c408a68cda
