### ISSUE TITLE
Consider using expand-file-name for destination

### ISSUE THREAD

**Issue by glynnforrest** [stsquad/dired-rsync#9]
Thanks for the brilliant package, I encountered the `ora-dired-rsync` defun through google and was looking to clean it up until I spotted you'd already done it.

Would it be possible to get the real path of the file using `expand-file-name`?

It'd be great to run `(dired-rsync "~/Desktop")` instead of `(dired-rsync (expand-file-name "~/Desktop"))`.

**Comment by glynnforrest** [comment]
Thanks. I looked into writing a patch but got scared off by the compat code for tramp, I'm not that familiar with it. It's no problem to expand the file name manually, I just thought I'd mention the potential for a small improvement. Feel free to close this issue if a fix would only complicate the code.

Having a single key to sync a load of files to the desktop is a total game changer for me, by the way. 👏

**Comment by stsquad** [comment]
@glynnforrest can you test and confirm master is OK for you?

**Comment by glynnforrest** [comment]
@stsquad Perfect, thank you for taking the time to do that!
